sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes

script:
  - pyflakes packtivity
  - pip install -e .
  - docker build -t lukasheinrich/packtivity .
  - echo {} > dummy.yml
  - packtivity-run dummy_analysis/dummystep.yml -s from-github dummy.yml dummy.yml
