sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes

script:
  - pyflakes yadage
  - pip install -e .
  - docker build -t lukasheinrich/packtivity .
  - ls -lrt /var/run
