sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes

script:
  - pyflakes packtivity
  - pip install -e .
  - docker build -t lukasheinrich/packtivity .
  - echo {} > dummy.yml
  - packtivity-run dummy_analysis/dummystep.yml -s from-github -c dummy.yml dummy.yml
  - "echo {'par_one': 1, 'par_two': 2, 'output': out} > pars.yml"
  - packtivity-run complex_analysis/getsignal.yml -s from-github pars.yml

